---
- name: Create cron_datasync scripts.d dir
  file:
    state=directory
    dest="{{ cron_datasync__sync_scripts_dir }}"
    mode="0755"

- name: Add scheduled run to cron.d
  template:
    src=cron_datasync.j2
    dest=/etc/cron.d/cron_datasync
    owner=root
    group=root
    mode=0644
