---
- hosts: all
  vars_files: 
    - config.yml
  tasks:
    - shell: "echo Provisioned on $(date) > {{ data_dir }}/provisioning.txt"
  roles:
    - { role: apt_basic, when: apt_basic.enabled }
    - { role: apt_localrepo, when: apt_localrepo.enabled }
    - { role: desktop, when: desktop.enabled }
    - { role: wikipedia, when: wikipedia.enabled }
    
    # Always run this one last, since it will build the ISO
    # if build_env.auto_iso is enabled in config.yml
    - { role: build_env, when: build_env.enabled }
    
  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
