---
- hosts: all
  vars:
    data_dir: "/usr/local/tunapanda"
    vagrant_share: "/vagrant"
    apache_dir: "/etc/apache2"
  vars_files:
    - config.yml
  tasks:
    - shell: "echo Provisioned on $(date) > {{ data_dir }}/provisioning.txt"
  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
  include: roles.yml
