---
##
## This file contains settings for a standalone ARM device that
## serves as a wireless access point and has edX pre-installed
##
- hosts: all
  pre_tasks:
    - shell: echo "Last provisioning started at $(date)" > {{ provision__base_dir }}/provisioning.txt
  post_tasks:
    - shell: echo "Last provisioning completed at $(date)" >> {{ provision__base_dir }}/provisioning.txt

  roles:
    - role: debops.ifupdown
    - role: provision_base
    - role: kalite
    - role: wap
    - role: edx_portal
    - role: iptables
    - role: vidtest
    - role: portal
    - role: cubietruck_net

  vars:
    # Common vars
    provision__base_dir: "/usr/local/tunapanda"
    provision__data_dir: "{{ provision__base_dir }}/data"
    provision__ext_dir: "{{ provision__base_dir }}/provision/ext"
    provision__default_packages: [ git, vim, screen ] 
    provision__sites_available_dir: "/etc/nginx/sites-available"
    provision__sites_enabled_dir: "/etc/nginx/sites-enabled"

    # TODO: split these off into roles?
    apache_dir: "/etc/apache2"
    apache_docroot: "/var/www"
    apache_user: "www-data"
    iptables__cmd: "/sbin/iptables"

    # Overrides for other roles
    ifupdown_external_interface: "eth1"
    ifupdown_internal_interface: "eth0"
    nginx_sites_available_dir: "{{ provision__sites_available_dir }}"
    nginx_sites_enabled_dir: "{{ provision__sites_enabled_dir }}"
    common_web_user: "www-data"
    EDXAPP_LMS_NGINX_PORT: '81'

    # CubieTruck specific
    ifupdown: True
    ifupdown_ignore_networkmanager: True
    ifupdown_external_interface: "eth0"
    ifupdown_internal_interface: "wlan0"
    ifupdown_interfaces: 
        - iface: "{{ ifupdown_external_interface  }}"
          inet: "dhcp"
        - iface: "{{ ifupdown_internal_interface }}"
          inet: "static"
          options: | 
            address 10.0.0.1
            netmask 255.0.0.0

    # Tell playbooks to assume edx is pre-installed
    # this changes what our options are for 
    # (re-)configuring it.
    edx__pre_installed: true
    provision__sites_available_dir: "/edx/app/nginx/sites-available/"
    provision__sites_enabled_dir: "/edx/app/nginx/sites-enabled/"
    php__fpm_url: "unix:/var/run/php5-fpm.sock"
    portal__auth: "agreement"
