---
##
## This file contains settings for a standalone classroom server
## It assumes that the server has a classroom LAN on the primary
## ethernet card, and (optionally) an Internet connection on the
## secondary card.
##
- hosts: all
  pre_tasks:
    - shell: echo "Last provisioning started at $(date)" > {{ provision__base_dir }}/provisioning.txt
  post_tasks:
    - shell: echo "Last provisioning completed at $(date)" >> {{ provision__base_dir }}/provisioning.txt

  roles:
    - role: debops.ifupdown
    - role: provision_base
    #- role: kalite
    #- role: vidtest
    - role: portal

  vars:
    # Common vars
    provision__base_dir: "/usr/local/tunapanda"
    provision__data_dir: "{{ provision__base_dir }}/data"
    provision__ext_dir: "{{ provision__base_dir }}/provision/ext"
    provision__default_packages: [ git, vim, screen ] 
    provision__sites_available_dir: "/etc/nginx/sites-available"
    provision__sites_enabled_dir: "/etc/nginx/sites-enabled"

    # TODO: split these off into roles?
    apache_dir: "/etc/apache2"
    apache_docroot: "/var/www"
    apache_user: "www-data"
    iptables__cmd: "/sbin/iptables"

    # Overrides for other roles
    ifupdown_external_interface: "eth1"
    ifupdown_internal_interface: "eth0"
    nginx_sites_available_dir: "{{ provision__sites_available_dir }}"
    nginx_sites_enabled_dir: "{{ provision__sites_enabled_dir }}"
    common_web_user: "www-data"
    EDXAPP_LMS_NGINX_PORT: '81'

    # Tunepanda server specific
    # Network setup
    ifupdown_internal_interface: eth0
    portal__auth: "auto"
    portal__redirect: "{{ ansible_eth0 }}"
    ifupdown: True
    ifupdown_ignore_networkmanager: True
    ifupdown_interfaces: 
        - iface: "{{ ifupdown_internal_interface }}"
          inet: 'static'
          options: | 
            address "10.0.0.1"
            netmask "255.0.0.0"
