---
- name: Ensuring that Apache is installed
  apt: 
    name=apache2 
    state=latest
    update_cache=yes
    cache_valid_time=600

- name: Ensuring that required Apache mods are enabled
  apache2_module: name={{ item }} state=present
  with_items:
    - rewrite
    - speling

- name: Add wikipedia aliases to /etc/hosts
  lineinfile: dest=/etc/hosts line="127.0.0.1 wikipedia www.wikipedia.org en.wikipedia.org wikipedia.org"
#- name: Install tunapanda-wikipedia
#  apt: name=tunapanda-wikipedia state=latest update_cache=yes force=yes
- name: Creating Apache config
  template:
      src="httpd-wikipedia.j2"
      dest={{ apache_dir }}/sites-available/tunapanda-wikipedia

- name: Linking Apache config
  file: 
    src:   "{{ apache_dir }}/sites-available/tunapanda-wikipedia" 
    path: "{{ apache_dir }}/sites-enabled/tunapanda-wikipedia"
    state: link
  notify:
    - restart apache
    
- name: Creating data dir {{ role_data_dir }}
  file: path={{ role_data_dir }} state=directory

- name: Checking mount status of {{ role_data_dir }}
  shell: mount | grep {{ role_data_dir }}
  register: is_mounted
  ignore_errors: True
  
- name: Mounting {{ role_data_dir }}
  command: mount --bind /vagrant/ansible/roles/wikipedia/data {{ role_data_dir }}
  when: is_mounted|failed
